# Generated by Django 5.0.3 on 2024-03-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=255)),
                ('carrying_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serial_number', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loc_pick_up', models.CharField(max_length=255)),
                ('loc_delivery', models.CharField(max_length=255)),
                ('weight', models.PositiveIntegerField(help_text='Введите вес в диапазоне от 1 до 1000')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
